apiVersion: v1
kind: Service
metadata:
  name: petik-backend-api-service
spec:
  selector:
    app: petik-backend-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer